default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: local
    hooks:
      - id: commit-style-check
        name: Custom commit message style check
        entry: uv run odev-commit-msg
        language: system
        stages: [commit-msg]
